#!/bin/sh
# autopkgtest check for metis
# (C) 2014 Anton Gladky

set -e

export OMPI_MCA_orte_rsh_agent=/bin/false

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cp graphs/* $WORKDIR/
cd $WORKDIR

graphchk 4elt.graph
graphchk copter2.graph
graphchk mdual.graph
graphchk test.mgraph

gpmetis 4elt.graph 10
gpmetis copter2.graph 10
gpmetis mdual.graph 10
gpmetis test.mgraph 10

mpmetis metis.mesh 4
m2gmetis metis.mesh 25
echo "run: OK"
